# Site settings
title: shangtian Blog
SEOTitle: shangtian的博客 | shangtian Blog
header-img: img/home-bg.jpg
email: alishangtian@gmail.com
description: "关于编程和生活 | shangtian，Java Lover，Software Engineer | 这里是 @shangtian的个人博客，与你一起发现Java的世界。"
keyword: "shangtian, Alishangtian,Java,分布式,大数据,Kafka,RocketMq,Dubbo,Etcd,K8s,Service Mesh,Istio,江湖名：墒田, 小米, 阿里巴巴,alishangtian.com, shangtian的博客"
url: "http://alishangtian.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
github_username:    alishangtian
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
# plugins: [jekyll-paginate,jekyll-admin]
plugins:
#  - jekyll-gist
#  - jekyll-coffeescript
#  - jekyll-assets
  - jekyll-paginate
# - jekyll-admin


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
# duoshuo_username: maoxiaobing
# duoshuo_share: true
# Netease settings
# netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: alishangtian.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next leap<br>我出生了，你的一切才刚开始"
sidebar-avatar: /img/avatar-maodou-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "Ismael Juma",
        href: "https://github.com/ijuma"
    },{
        title: "Patrick Hunt",
        href: "https://github.com/phunt"
    },{
        title: "Evan Zhou",
        href: "https://github.com/coocood"
    },{
        title: "Fangjin Yang",
        href: "https://github.com/fjy"
    },{
        title: "Trustin Lee",
        href: "https://github.com/trustin"
    },{
        title: "Peter Zhu",
        href: "https://github.com/nkorange"
    },{
        title: "Craig Tiller",
        href: "https://github.com/ctiller"
    },{
        title: "Jon Skeet",
        href: "https://github.com/jskeet"
    },{
        title: "yukon",
        href: "https://github.com/zhouxinyu"
    },{
        title: "shangtian",
        href: "https://github.com/alishangtian"
    }
]
